/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.EmployeeController;
import java.awt.Component;
import java.awt.Window;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import models.Employees;

/**
 *
 * @author GL503
 */
public class AddNewEmployee extends javax.swing.JPanel {

    /**
     * Creates new form AddNewEmployees
     */
    public AddNewEmployee() {
        initComponents();

        baseSalaryField.setVisible(false);
        baseSalaryLabel.setVisible(false);

        totalSalesField.setVisible(false);
        totalSalesLabel.setVisible(false);

        totalHoursWorkedField.setVisible(false);
        totalHoursWorkedLabel.setVisible(false);

        ratePerHourField.setVisible(false);
        ratePerHourLabel.setVisible(false);

        ratePerPieceField.setVisible(false);
        ratePerPieceLabel.setVisible(false);

        totalPiecesFinishedField.setVisible(false);
        totalPiecesFinishedLabel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderButtonGroup = new javax.swing.ButtonGroup();
        idLabel = new javax.swing.JLabel();
        firstNameLabel = new javax.swing.JLabel();
        middleNameLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        genderLabel = new javax.swing.JLabel();
        jobLabel = new javax.swing.JLabel();
        typeLabel = new javax.swing.JLabel();
        jobField = new javax.swing.JTextField();
        firstNameField = new javax.swing.JTextField();
        middleNameField = new javax.swing.JTextField();
        lastNameField = new javax.swing.JTextField();
        idField = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        femaleRadio = new javax.swing.JRadioButton();
        maleRadio = new javax.swing.JRadioButton();
        employeeType = new javax.swing.JComboBox<>();
        baseSalaryField = new javax.swing.JTextField();
        baseSalaryLabel = new javax.swing.JLabel();
        totalSalesLabel = new javax.swing.JLabel();
        totalSalesField = new javax.swing.JTextField();
        totalHoursWorkedField = new javax.swing.JTextField();
        totalHoursWorkedLabel = new javax.swing.JLabel();
        ratePerHourLabel = new javax.swing.JLabel();
        ratePerHourField = new javax.swing.JTextField();
        ratePerPieceLabel = new javax.swing.JLabel();
        ratePerPieceField = new javax.swing.JTextField();
        totalPiecesFinishedLabel = new javax.swing.JLabel();
        totalPiecesFinishedField = new javax.swing.JTextField();
        insertNewEmployeeLabel = new javax.swing.JLabel();
        employeeTableButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        idLabel.setText("ID:");
        add(idLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        firstNameLabel.setText("First Name:");
        add(firstNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 70, 30));

        middleNameLabel.setText("Middle Name (Optional):");
        add(middleNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, 20));

        lastNameLabel.setText("Last Name:");
        add(lastNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 80, 20));

        genderLabel.setText("Gender:");
        add(genderLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        jobLabel.setText("Job:");
        add(jobLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));

        typeLabel.setText("Type:");
        add(typeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, -1, -1));
        add(jobField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 160, -1));
        add(firstNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 160, -1));
        add(middleNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 160, -1));

        lastNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameFieldActionPerformed(evt);
            }
        });
        add(lastNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 160, -1));
        add(idField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 160, -1));

        addButton.setText("ADD");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        add(addButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 540, -1, -1));

        genderButtonGroup.add(femaleRadio);
        femaleRadio.setText("Female");
        add(femaleRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, -1, -1));

        genderButtonGroup.add(maleRadio);
        maleRadio.setText("Male");
        maleRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleRadioActionPerformed(evt);
            }
        });
        add(maleRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, -1, -1));

        employeeType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Type", "Base Plus Commission Employee", "Commission Employee", "Hourly Employee", "Piece Worker Employee" }));
        employeeType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeTypeActionPerformed(evt);
            }
        });
        add(employeeType, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 160, -1));

        baseSalaryField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baseSalaryFieldActionPerformed(evt);
            }
        });
        add(baseSalaryField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 460, 160, -1));

        baseSalaryLabel.setText("Base Salary:");
        add(baseSalaryLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, -1, -1));

        totalSalesLabel.setText("Total Sales:");
        add(totalSalesLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, -1, -1));
        add(totalSalesField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, 160, -1));
        add(totalHoursWorkedField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 460, 160, -1));

        totalHoursWorkedLabel.setText("Total Hours Worked:");
        add(totalHoursWorkedLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, -1, -1));

        ratePerHourLabel.setText("Rate Per Hour:");
        add(ratePerHourLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, -1, -1));
        add(ratePerHourField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, 160, -1));

        ratePerPieceLabel.setText("Rate Per Piece:");
        add(ratePerPieceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, -1, -1));
        add(ratePerPieceField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, 160, -1));

        totalPiecesFinishedLabel.setText("Total Pieces Finished:");
        add(totalPiecesFinishedLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, -1, -1));
        add(totalPiecesFinishedField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 460, 160, -1));

        insertNewEmployeeLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        insertNewEmployeeLabel.setText("INSERT NEW EMPLOYEE");
        add(insertNewEmployeeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 310, -1));

        employeeTableButton.setText("Go to Employee Table");
        employeeTableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeTableButtonActionPerformed(evt);
            }
        });
        add(employeeTableButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void lastNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameFieldActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:

        //CODE TO ADD
        try {
            maleRadio.setActionCommand("Male");
            femaleRadio.setActionCommand("Female");
            String gender = genderButtonGroup.getSelection().getActionCommand();

            int id = Integer.parseInt(idField.getText());
            String firstName = firstNameField.getText();
            String middleName = middleNameField.getText();
            String lastName = lastNameField.getText();
            String job = jobField.getText();
            String jobType = (String) employeeType.getSelectedItem();
            Double salary = Double.parseDouble(baseSalaryField.getText());

            Employees emp = new Employees(id, firstName, middleName, lastName, gender, job, jobType, salary);

            EmployeeController empC = new EmployeeController();

            if (empC.insertEmployee(emp) == 1) {

                int rep = JOptionPane.showConfirmDialog(null, "New Employee Added!!", "Notif", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE);
                if (rep == 0) {
                    Component comp = SwingUtilities.getRoot(this);
                    ((Window) comp).dispose();
                    EmployeeTableList etl = new EmployeeTableList();
                    JFrame jf = new JFrame("Employee Management");
                    jf.add(etl);
                    jf.setSize(600, 550);
                    jf.setResizable(false);
                    jf.setVisible(true);
                }
            } else {
                JOptionPane.showConfirmDialog(null, "Insert Error!", "Notif", JOptionPane.DEFAULT_OPTION, JOptionPane.ERROR_MESSAGE);
            }
        } catch (NullPointerException e) {
            JOptionPane.showConfirmDialog(null, "Insert Error! Details Lacking!", "Notif", JOptionPane.DEFAULT_OPTION, JOptionPane.ERROR_MESSAGE);
        }

        //
        //        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void maleRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleRadioActionPerformed

    private void employeeTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeTypeActionPerformed
        // TODO add your handling code here:
        String chosenEmployeeType = (String) employeeType.getSelectedItem();
        if (chosenEmployeeType.equals("Choose Type")) {
            baseSalaryField.setVisible(false);
            baseSalaryLabel.setVisible(false);

            totalSalesField.setVisible(false);
            totalSalesLabel.setVisible(false);

            totalHoursWorkedField.setVisible(false);
            totalHoursWorkedLabel.setVisible(false);

            ratePerHourField.setVisible(false);
            ratePerHourLabel.setVisible(false);

            ratePerPieceField.setVisible(false);
            ratePerPieceLabel.setVisible(false);

            totalPiecesFinishedField.setVisible(false);
            totalPiecesFinishedLabel.setVisible(false);

        } else if (chosenEmployeeType.equals("Base Plus Commission Employee")) {
            baseSalaryField.setVisible(true);
            baseSalaryLabel.setVisible(true);

            totalSalesField.setVisible(true);
            totalSalesLabel.setVisible(true);

            totalHoursWorkedField.setVisible(false);
            totalHoursWorkedLabel.setVisible(false);

            ratePerHourField.setVisible(false);
            ratePerHourLabel.setVisible(false);

            ratePerPieceField.setVisible(false);
            ratePerPieceLabel.setVisible(false);

            totalPiecesFinishedField.setVisible(false);
            totalPiecesFinishedLabel.setVisible(false);

        } else if (chosenEmployeeType.equals("Commission Employee")) {
            baseSalaryField.setVisible(false);
            baseSalaryLabel.setVisible(false);

            totalSalesField.setVisible(true);
            totalSalesLabel.setVisible(true);

            totalHoursWorkedField.setVisible(false);
            totalHoursWorkedLabel.setVisible(false);

            ratePerHourField.setVisible(false);
            ratePerHourLabel.setVisible(false);

            ratePerPieceField.setVisible(false);
            ratePerPieceLabel.setVisible(false);

            totalPiecesFinishedField.setVisible(false);
            totalPiecesFinishedLabel.setVisible(false);

        } else if (chosenEmployeeType.equals("Hourly Employee")) {
            baseSalaryField.setVisible(false);
            baseSalaryLabel.setVisible(false);

            totalSalesField.setVisible(false);
            totalSalesLabel.setVisible(false);

            totalHoursWorkedField.setVisible(true);
            totalHoursWorkedLabel.setVisible(true);

            ratePerHourField.setVisible(true);
            ratePerHourLabel.setVisible(true);

            ratePerPieceField.setVisible(false);
            ratePerPieceLabel.setVisible(false);

            totalPiecesFinishedField.setVisible(false);
            totalPiecesFinishedLabel.setVisible(false);

        } else if (chosenEmployeeType.equals("Piece Worker Employee")) {
            baseSalaryField.setVisible(false);
            baseSalaryLabel.setVisible(false);

            totalSalesField.setVisible(false);
            totalSalesLabel.setVisible(false);

            totalHoursWorkedField.setVisible(false);
            totalHoursWorkedLabel.setVisible(false);

            ratePerHourField.setVisible(false);
            ratePerHourLabel.setVisible(false);

            ratePerPieceField.setVisible(true);
            ratePerPieceLabel.setVisible(true);

            totalPiecesFinishedField.setVisible(true);
            totalPiecesFinishedLabel.setVisible(true);

        }
    }//GEN-LAST:event_employeeTypeActionPerformed

    private void baseSalaryFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baseSalaryFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_baseSalaryFieldActionPerformed

    private void employeeTableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeTableButtonActionPerformed
        // TODO add your handling code here:
        Component comp = SwingUtilities.getRoot(this);
        ((Window) comp).dispose();
        EmployeeTableList etl = new EmployeeTableList();
        JFrame jf = new JFrame("Employee Management");
        jf.add(etl);
        jf.setSize(600, 500);
        jf.setResizable(false);
        jf.setVisible(true);
    }//GEN-LAST:event_employeeTableButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JTextField baseSalaryField;
    private javax.swing.JLabel baseSalaryLabel;
    private javax.swing.JButton employeeTableButton;
    private javax.swing.JComboBox<String> employeeType;
    private javax.swing.JRadioButton femaleRadio;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.ButtonGroup genderButtonGroup;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel insertNewEmployeeLabel;
    private javax.swing.JTextField jobField;
    private javax.swing.JLabel jobLabel;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JRadioButton maleRadio;
    private javax.swing.JTextField middleNameField;
    private javax.swing.JLabel middleNameLabel;
    private javax.swing.JTextField ratePerHourField;
    private javax.swing.JLabel ratePerHourLabel;
    private javax.swing.JTextField ratePerPieceField;
    private javax.swing.JLabel ratePerPieceLabel;
    private javax.swing.JTextField totalHoursWorkedField;
    private javax.swing.JLabel totalHoursWorkedLabel;
    private javax.swing.JTextField totalPiecesFinishedField;
    private javax.swing.JLabel totalPiecesFinishedLabel;
    private javax.swing.JTextField totalSalesField;
    private javax.swing.JLabel totalSalesLabel;
    private javax.swing.JLabel typeLabel;
    // End of variables declaration//GEN-END:variables
}
