/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.EmployeeController;
import java.awt.Component;
import java.awt.Window;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import models.Employees;

/**
 *
 * @author GL503
 */
public class DeleteEmployee extends javax.swing.JPanel {

    /**
     * Creates new form DeleteEmployees
     */
    public DeleteEmployee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deleteButton = new javax.swing.JButton();
        idField = new javax.swing.JTextField();
        idLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        employeeTableButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        add(deleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, -1, -1));
        add(idField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 90, -1));

        idLabel.setText("ID:");
        add(idLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("DELETE EMPLOYEE");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));

        employeeTableButton.setText("Back to Employee Table");
        employeeTableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeTableButtonActionPerformed(evt);
            }
        });
        add(employeeTableButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 170, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        try {
            int rc = JOptionPane.showConfirmDialog(null, "Procced?", "Confirmation", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

            //CODE TO DELETE
            Employees emp = new Employees();
            emp.deleteEmployees(Integer.parseInt(idField.getText()));
            EmployeeController empC = new EmployeeController();

            //System.out.println(emp.getId());
            if (empC.deleteEmployee(emp) == 1 && rc == 0) {
                int rep = JOptionPane.showConfirmDialog(null, "DELETE SUCCESS!", "Notif", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE);
                if (rep == 0) {
                    Component comp = SwingUtilities.getRoot(this);
                    ((Window) comp).dispose();
                    EmployeeTableList etl = new EmployeeTableList();
                    JFrame jf = new JFrame("Employee Management");
                    jf.add(etl);
                    jf.setSize(600, 550);
                    jf.setResizable(false);
                    jf.setVisible(true);
                }
            } else {
                JOptionPane.showConfirmDialog(null, "Delete Error! ID not found", "Notif", JOptionPane.DEFAULT_OPTION, JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showConfirmDialog(null, "Delete Error! ID input error!", "Notif", JOptionPane.DEFAULT_OPTION, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void employeeTableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeTableButtonActionPerformed
        // TODO add your handling code here:
        Component comp = SwingUtilities.getRoot(this);
        ((Window) comp).dispose();
        EmployeeTableList etl = new EmployeeTableList();
        JFrame jf = new JFrame("Employee Management");
        jf.add(etl);
        jf.setSize(600, 550);
        jf.setResizable(false);
        jf.setVisible(true);
    }//GEN-LAST:event_employeeTableButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton employeeTableButton;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
