/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.Component;
import java.awt.Window;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author GL503
 */
public class EmployeeMainMenu extends javax.swing.JPanel {

    /**
     * Creates new form EmployeeMainMenu
     */
    public EmployeeMainMenu() {
        initComponents();
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        employeeManagementButton = new javax.swing.JButton();
        accountButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        employeeManagementButton.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        employeeManagementButton.setText("Employee Management");
        employeeManagementButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeManagementButtonActionPerformed(evt);
            }
        });
        add(employeeManagementButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, 71));

        accountButton.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        accountButton.setText("Settings");
        accountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountButtonActionPerformed(evt);
            }
        });
        add(accountButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 170, 70));

        logoutButton.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        add(logoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 150, 70));
    }// </editor-fold>//GEN-END:initComponents

    private void employeeManagementButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeManagementButtonActionPerformed
        // TODO add your handling code here:
        Component comp = SwingUtilities.getRoot(this);
        ((Window) comp).dispose();
        EmployeeTableList etl = new EmployeeTableList();
        JFrame jf = new JFrame("Employee Management");
        jf.add(etl);
        jf.setSize(600, 550);
        jf.setResizable(false);
        jf.setVisible(true);

    }//GEN-LAST:event_employeeManagementButtonActionPerformed

    private void accountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountButtonActionPerformed
        // TODO add your handling code here:
        Component comp = SwingUtilities.getRoot(this);
        ((Window) comp).dispose();

        Settings set = new Settings();
        JFrame jf = new JFrame("Settings");
        jf.add(set);
        jf.setSize(450, 450);
        jf.setResizable(false);
        jf.setVisible(true);
    }//GEN-LAST:event_accountButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        Component comp = SwingUtilities.getRoot(this);
        ((Window) comp).dispose();
        EmployeeLogin eml = new EmployeeLogin();
        JFrame jf = new JFrame("Login");
        jf.add(eml);
        jf.setSize(400, 400);
        jf.setVisible(true);

    }//GEN-LAST:event_logoutButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accountButton;
    private javax.swing.JButton employeeManagementButton;
    private javax.swing.JButton logoutButton;
    // End of variables declaration//GEN-END:variables
}
