/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.EmployeeController;
import java.awt.Component;
import java.awt.Window;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import models.Employees;

/**
 *
 * @author GL503
 */
public class EmployeeTableList extends javax.swing.JPanel {

    /**
     * Creates new form EmployeeTableList
     */
    public EmployeeTableList() {
        initComponents();
        List<Employees> empList = EmployeeController.getAllRecords();

        DefaultTableModel model = (DefaultTableModel) employeeListTable.getModel();
        for (Employees empDetails:empList){
            String name = empDetails.getFirstName() + " " + empDetails.getMiddleName() + " " + empDetails.getLastName();
            model.addRow(new Object[]{empDetails.getId(), name, empDetails.getGender(), empDetails.getJob(), empDetails.getJobType(), empDetails.getSalary()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addNewEmployeeButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        employeeListTable = new javax.swing.JTable();
        updateEmployeeButton = new javax.swing.JButton();
        deleteEmployeeButton = new javax.swing.JButton();
        employeeMainMenuButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addNewEmployeeButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addNewEmployeeButton.setText("Add New Employee");
        addNewEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewEmployeeButtonActionPerformed(evt);
            }
        });
        add(addNewEmployeeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, -1, 40));

        employeeListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Gender", "Job", "Type", "Salary"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(employeeListTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, 321));

        updateEmployeeButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        updateEmployeeButton.setText("Update Employee");
        updateEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateEmployeeButtonActionPerformed(evt);
            }
        });
        add(updateEmployeeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, 140, 40));

        deleteEmployeeButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        deleteEmployeeButton.setText("Delete Employee");
        deleteEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteEmployeeButtonActionPerformed(evt);
            }
        });
        add(deleteEmployeeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 430, 140, 40));

        employeeMainMenuButton.setText("Return to Main Menu");
        employeeMainMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeMainMenuButtonActionPerformed(evt);
            }
        });
        add(employeeMainMenuButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void addNewEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewEmployeeButtonActionPerformed
        // TODO add your handling code here:
        Component comp = SwingUtilities.getRoot(this);
        ((Window) comp).dispose();
        AddNewEmployee ane = new AddNewEmployee();
        JFrame jf = new JFrame("Employee Management: Insert New Employee");
        jf.add(ane);
        jf.setSize(450, 650);
        jf.setResizable(false);
        jf.setVisible(true);
    }//GEN-LAST:event_addNewEmployeeButtonActionPerformed

    private void updateEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateEmployeeButtonActionPerformed
        // TODO add your handling code here:
        Component comp = SwingUtilities.getRoot(this);
        ((Window) comp).dispose();
        EditEmployee ee = new EditEmployee();
        JFrame jf = new JFrame("Employee Management: Update New Employee");
        jf.add(ee);
        jf.setSize(450, 650);
        jf.setResizable(false);
        jf.setVisible(true);
    }//GEN-LAST:event_updateEmployeeButtonActionPerformed

    private void deleteEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteEmployeeButtonActionPerformed
        // TODO add your handling code here:
        Component comp = SwingUtilities.getRoot(this);
        ((Window) comp).dispose();
        DeleteEmployee de = new DeleteEmployee();
        JFrame jf = new JFrame("Employee Management: Delete Employee");
        jf.add(de);
        jf.setSize(600, 550);
        jf.setResizable(false);
        jf.setVisible(true);
    }//GEN-LAST:event_deleteEmployeeButtonActionPerformed

    private void employeeMainMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeMainMenuButtonActionPerformed
        // TODO add your handling code here:
        Component comp = SwingUtilities.getRoot(this);
        ((Window) comp).dispose();
        EmployeeMainMenu emm = new EmployeeMainMenu();
        JFrame jf = new JFrame("Employee Main Menu");
        jf.add(emm);
        jf.setSize(664, 140);
        jf.setResizable(false);
        jf.setVisible(true);
    }//GEN-LAST:event_employeeMainMenuButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNewEmployeeButton;
    private javax.swing.JButton deleteEmployeeButton;
    private javax.swing.JTable employeeListTable;
    private javax.swing.JButton employeeMainMenuButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton updateEmployeeButton;
    // End of variables declaration//GEN-END:variables
}
