/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.EmployeeController;
import java.awt.Component;
import java.awt.Window;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import models.User;

/**
 *
 * @author GL503
 */
public class Settings extends javax.swing.JPanel {

    /**
     * Creates new form Setting
     */
    User u = new User();

    User userRec = EmployeeController.getRecordUser(u);

    EmployeeController empC = new EmployeeController();

    public Settings() {
        initComponents();

        usernameField.setText(userRec.getUsername());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        menuButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        currentPasswordField = new javax.swing.JPasswordField();
        newPasswordField = new javax.swing.JPasswordField();
        retypeNewPasswordField = new javax.swing.JPasswordField();
        confirmButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Username:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        menuButton.setText("Return to Main Menu");
        menuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButtonActionPerformed(evt);
            }
        });
        add(menuButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Current Password:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("New Password:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Re-type new Password:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        usernameField.setEditable(false);
        add(usernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 180, -1));
        add(currentPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 180, -1));
        add(newPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 180, -1));
        add(retypeNewPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 180, -1));

        confirmButton.setText("Confirm");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });
        add(confirmButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        // TODO add your handling code here:
        String currPass = userRec.getPassword();
        String inputCurrPass = currentPasswordField.getText();
        int rc = JOptionPane.showConfirmDialog(null, "Procced?", "Confirmation", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (rc == 0 && currPass.equals(inputCurrPass)) {
            String newPassword = newPasswordField.getText();
            String retypeNewPassword = retypeNewPasswordField.getText();

            if (newPassword.equals(null)) {
                JOptionPane.showConfirmDialog(null, "UPDATE ERROR! Fill up form!", "Notif", JOptionPane.DEFAULT_OPTION, JOptionPane.ERROR_MESSAGE);
            } else if (newPassword.equals(retypeNewPassword)) {
                u.setPassword(newPassword);
                if(empC.updateUser(u)==1){
                    int rep = JOptionPane.showConfirmDialog(null, "UPDATE SUCCESS!", "Notif", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE);
                    if (rep == 0) {
                        Component comp = SwingUtilities.getRoot(this);
                        ((Window) comp).dispose();
                        EmployeeMainMenu emm = new EmployeeMainMenu();
                        JFrame jf = new JFrame("Employee Main Menu");
                        jf.add(emm);
                        jf.setSize(664, 140);
                        jf.setResizable(false);
                        jf.setVisible(true);
                    }
                }
                
            } else {
                JOptionPane.showConfirmDialog(null, "UPDATE ERROR! Retype New Password is not the same with New Password!", "Notif", JOptionPane.DEFAULT_OPTION, JOptionPane.ERROR_MESSAGE);
            }

        } else {
            JOptionPane.showConfirmDialog(null, "UPDATE ERROR! Current Password Wrong!", "Notif", JOptionPane.DEFAULT_OPTION, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_confirmButtonActionPerformed

    private void menuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuButtonActionPerformed
        // TODO add your handling code here:
        Component comp = SwingUtilities.getRoot(this);
        ((Window) comp).dispose();
        EmployeeMainMenu emm = new EmployeeMainMenu();
        JFrame jf = new JFrame("Employee Main Menu");
        jf.add(emm);
        jf.setSize(664, 140);
        jf.setResizable(false);
        jf.setVisible(true);
    }//GEN-LAST:event_menuButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirmButton;
    private javax.swing.JPasswordField currentPasswordField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton menuButton;
    private javax.swing.JPasswordField newPasswordField;
    private javax.swing.JPasswordField retypeNewPasswordField;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
